# See https://directus.io/docs/getting-started/create-a-project#docker-compose
services:
  directus:
    image: directus/directus:11.14.1
    container_name: directus-cms
    ports:
      - 8055:8055
    volumes:
      - ~/directus/database:/directus/database
      - ~/directus/uploads:/directus/uploads
      - ~/directus/extensions:/directus/extensions
    environment:
      SECRET: ${SECRET}
      DB_CLIENT: ${DB_CLIENT}
      DB_FILENAME: ${DB_FILENAME}
      WEBSOCKETS_ENABLED: "true"
